routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

//Route::get('/branches','BranchController@Index')->name('branches.index');
//Route::get('/branches/create','BranchController@create')->name('branches.create');
//Route::get('/branches/edit/{id}','BranchController@edit')->name('branches.edit');
//Route::get('/branches/delete/{id}','BranchController@delete')->name('branches.delete');

//Route::post('/branches/store','BranchController@store');
//Route::patch('/branches/update/{id}','BranchController@update');

Route::get('/login','loginController@index')->name('login');
Route::post('/login-new','loginController@store')->name('pasok');
Route::get('/logout','loginController@logout')->name('gawas');

Route::resource('/branches','BranchController');
Route::get('/branches/delete/{id}','BranchController@delete')->name('branches.delete');

Route::resource('/employees','EmployeeController');
Route::get('/employees/delete/{id}','EmployeeController@delete')->name('employees.delete');

Route::resource('/customers','CustomerController');
Route::get('/customers/delete/{id}','CustomerController@delete')->name('customers.delete');

Route::resource('/users','UserController');
Route::get('/users/delete/{id}','UserController@delete')->name('users.delete');

app/Customer.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Customer extends Model
{
    protected $guarded = [];
}

app/Http/Controllers/CustomerController.php
<?php

namespace App\Http\Controllers;

use App\Branch;
use App\Employee;
use Request;
use Validator;
use Auth;

class EmployeeController extends Controller
{
    public function __construct()
    {
        $this->middleware('auth');
    }

    public function index()
    {
        $employees = Employee::paginate(5);
        return view('employees.index',compact('employees'));
    }

    public function create()
    {
        $branches = Branch::pluck('name','id');
        return view('employees.create',compact('branches'));
    }

    public function store()
    {
        $validator = Validator::make(Request::all(), [
            'branch_id'            =>  'required',
            'name'                 =>  'required',
            'address'              =>  'required',
        ],
        [
            'branch_id.required'   =>  'Select Branch Required',
            'name.required'        =>  'Employee Name Required',
            'address.required'     =>  'Employee Address Required',

        ]);


        if ($validator->fails()) {
            return redirect()->back()
                ->withErrors($validator)
                ->withInput();
        }

        Employee::create(Request::all());
        toastr()->success('Employee has been saved successfully!');
        return redirect()->back();
    }

    public function edit($id)
    {
        $employee = Employee::find($id);
        return view('employees.edit',compact('employee'));
    }

    public function update($id)
    {
        $employee = Employee::find($id);
        $validator = Validator::make(Request::all(), [
            'name'                 =>  "required|unique:employees,name,$employee->id,id",
            'address'              =>  "required|unique:employees,address,$employee->id,id",
        ],
        [
            'name.required'        =>  'Employee Name Required',
            'address.required'     =>  'Employee Address Required',
        ]);
        if ($validator->fails()) {
            return redirect()->back()
                        ->withErrors($validator)
                        ->withInput();
        }

        $employee->update(Request::all());
        toastr()->success('Data has been updated successfully!');
        return redirect()->route('employees.index');

    }

    public function delete($id)
    {
        $employee = Employee::find($id);
        toastr()->success('Data has been deleted successfully!');
        $employee->delete();
        return redirect()->route('employees.index');
    }
}

resources/views/customers/create.blade.php
@extends('layouts.app')
@section('content')
<h1 class="page-title mt-2">Customer Module - Create</h1>
<div class="row">
    <div class="col-12">
        <a href="{{ route('customers.index') }}" class="btn btn-primary mb-1">Back to Index</a>
        {!! Form::open(['method'=>'POST','action'=>'CustomerController@store']) !!}
        @include('alert')
        <div class="card mt-3">
            <div class="card-header">Add Customer</div>
            <div class="card-body">
                <div class="mb-3">
                    {!! Form::label('Enter Name') !!}
                    {!! Form::text('name',null,['class'=>'form-control']) !!}
                </div>
                <div class="mb-3">
                    {!! Form::label('Enter Name') !!}
                    {!! Form::text('name',null,['class'=>'form-control']) !!}
                </div>
                <div class="mb-3">
                    {!! Form::label('Enter Address') !!}
                    {!! Form::text('address',null,['class'=>'form-control']) !!}
                </div>
            </div>
            <div class="card-footer">
                {!! Form::submit('Save Entry',['class'=>'btn btn-primary']) !!}
            </div>
        </div>
        {!! Form::close() !!}
    </div>
</div>    
@endsection

resources/views/customers/edit.blade.php
@extends('layouts.app')
@section('content')
<h1 class="page-title mt-2">Customer Module - Edit {{ $customer->name }}</h1>
<div class="row">
    <div class="col-12">
        <a href="{{ route('customers.index') }}" class="btn btn-primary mb-1">Back to Index</a>
        {!! Form::model($employee,['method'=>'PATCH','action'=>['CustomerController@update',$customer->id]]) !!}
        @include('alert')
        <div class="card mt-3">
            <div class="card-header">Edit Customer</div>
            <div class="card-body">
                <div class="mb-3">
                    {!! Form::label('Agent') !!}
                    {!! Form::text('codes',null,['class'=>'form-control']) !!}
                </div>
                <div class="mb-3">
                    {!! Form::label('Enter Name') !!}
                    {!! Form::text('address',null,['class'=>'form-control']) !!}
                </div>
                <div class="mb-3">
                    {!! Form::label('Enter Address') !!}
                    {!! Form::text('address',null,['class'=>'form-control']) !!}
                </div>
            </div>
            <div class="card-footer">
                {!! Form::submit('Update Entry',['class'=>'btn btn-primary']) !!}
            </div>
        </div>
        {!! Form::close() !!}
    </div>
</div>    
@endsection

resources/views/customers/index.blade.php
@extends('layouts.app')
@section('content')
<h1 class="page-title">Customer Module</h1>
<div class="row">
    <div class="col-12">
        <a href="{{ route('customers.create') }}" class="btn btn-primary mb-1">Create Entry</a>
        <table class="table table-striped">
            <thead>
                <tr>
                    <th class="text-center">ID</th>
                    <th class="text-center">Agent</th>
                    <th class="text-center">Name</th>
                    <th class="text-center">Address</th>
                    <th class="text-center">Action</th>
                </tr>
            </thead>
            <tbody>
                @foreach ($customers as $data)
                <tr>
                    <td class="text-center">{{ $data->id }}</td>
                    <td class="text-center">{{ $data->employee_name }}</td>
                    <td class="text-center">{{ $data->name}}</td>
                    <td class="text-center">{{ $data->address}}</td>
                    <td class="text-center">
                        <a href="{{ action('CustomerController@edit',$data->id) }}" class="btn btn-success">Edit</a>  
                        <a href="{{ action('CustomerController@delete',$data->id) }}" class="btn btn-danger">Delete</a>
                    </td>
                </tr>
                @endforeach
            </tbody>
        </table>
        {!! $customers->links() !!}
    </div>
</div>
@endsection